[tool.hatch.build.targets.sdist]
include = ["src/*"]
exclude = ["tests/*"] # on this later

[tool.hatch.build.targets.wheel]
include = ["src/*"]
exclude = ["tests/*"] # on this later

[tool.hatch.build.targets.wheel.sources]
"src/concept_learner" = "concept_learner"

[build-system]
requires = ["hatchling"]
build-backend = "hatchling.build"

[project]
name = "concept-learner"
version = "0.1.0"
description = ""
requires-python = ">=3.13"
authors = [{ name = "Debjit Biswas" }]
license = "BSD-3-Clause"
readme = "README.md"
dependencies = [
    "pyrootutils",
    "loguru",
    "torch>=2.8.0",
    "tokenizers>=0.21.4",
    "transformers>=4.55.4",
]

[dependency-groups]
dev = [
    "mypy",
    "ruff",
    "pytest",
    "pytest-cov",
    "pytest-mock",
    "pytest-pylint",
    "pytest-mypy",
    "pytest-testmon",
    "pytest-xdist",
    "nbmake",
]

[tool.uv]

[[tool.uv.index]]
name = "pypi"
url = "https://pypi.org/simple"
default = true

[[tool.uv.index]]
name = "pytorch"
url = "https://download.pytorch.org/whl/cpu"
explicit = true

[tool.uv.sources]
torch = [
    { index = "pytorch", marker = "sys_platform == 'linux'" },
    { index = "pypi", marker = "sys_platform == 'darwin'" },
]
