[tool.poetry]
name = "concept-learner"
version = "0.1.0"
description = ""
authors = ["Debjit Biswas <debjit@fastmail.fm>"]
readme = "README.md"

[tool.poetry.dependencies]
python = ">=3.10,<3.14"
torch = "2.8"
numpy = "2.2"
gradio = "^5.43.1"
openai = "^1.40.0"


[build-system]
requires = ["poetry-core"]
build-backend = "poetry.core.masonry.api"
